_sensio_training:
    resource: "@SensioTrainingBundle/Controller/"
    type:     annotation
    prefix:   /

homepage:
    path: /
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
        route: dude_list
