# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']

    # app.monolog.processor.web_processor:
    #     class: Monolog\Processor\WebProcessor
    #     tags:
    #         - { name: monolog.processor }

    app.monolog.processor.id_processor:
        class: AppBundle\Monolog\Processor\IdProcessor
        tags:
            - { name: monolog.processor }
