<?php

namespace Sensio\Bundle\TrainingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DudeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DudeRepository extends EntityRepository
{
}
